# NUMPY BASIC ASSIGNMENT 

Consider the below code to answer further questions:

import numpy as np

list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]

array_list = np.array(object = list_)

**Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.**

Solution:

The variable list_ is a Python list, which can contain elements of different data types. In this case, the elements in list_ are strings.

The variable array_list is a NumPy array, which is a homogeneous data structure. It can only store elements of the same data type. In this case, since the original list contains strings, the resulting NumPy array will also have string elements.

To print the data types of both variables, you can use the type() function in Python. Here's is an example:

In [1]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(list_)

print("Data type of list_:", type(list_))
print("Data type of array_list:", type(array_list))


Data type of list_: <class 'list'>
Data type of array_list: <class 'numpy.ndarray'>


**Q2. Write a code to print the data type of each and every element of both the variables list_ and
array_list.**

Solution:

In [2]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(list_)

print("Data type of each element in list_:")
for element in list_:
    print(type(element))

print("Data type of each element in array_list:")
for element in array_list:
    print(element.dtype)


Data type of each element in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
Data type of each element in array_list:
<U1
<U1
<U1
<U1
<U1


**Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)
Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.**

Solution:

there will be a difference in the data type of the elements present in the variables list_ and array_list after the change is made to the array_list variable.

In the updated code where array_list is defined as np.array(object=list_, dtype=int), the dtype parameter is set to int. This specifies that the elements in array_list should be converted to integer data type.

In [3]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype=int)

print("Data type of each element in list_:")
for element in list_:
    print(type(element))

print("Data type of each element in array_list:")
for element in array_list:
    print(type(element))

    

Data type of each element in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
Data type of each element in array_list:
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


# Consider the below code to answer further questions:
import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)

**Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size**

Solution:

In [4]:
import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(num_list)

# (i) Shape
print("Shape of num_array:", num_array.shape)

# (ii) Size
print("Size of num_array:", num_array.size)


Shape of num_array: (2, 3)
Size of num_array: 6


**Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]**

Solution:

In [5]:
import numpy as np

zero_array = np.zeros((3, 3))

print(zero_array)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


**Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]**

Solution:

In [6]:
import numpy as np

identity_matrix = np.eye(5)

print(identity_matrix)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


# ------------------------------------------------END---------------------------------------------------------